temp/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>GameId__c</fullName>
        <externalId>true</externalId>
        <label>GameId</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Game</label>
    <nameField>
        <label>Matchup</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Player__c.object
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Season__c.object
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/test_DetailCardsController.cls
@isTest
private class test_DetailCardsController {
	@isTest
    static void testGetCurrentSeasonId() {
        SObjectFactory seasonFactory = new test_f_SeasonFactory();
        seasonFactory.buildAndInsertRecords(10);
        
        Test.startTest();
        Id seasonId = page_DetailCardsController.getCurrentSeasonId();
        Test.stopTest();
        
        System.assertNotEquals(true, seasonId == null, 'returned Id should not have been null');
    }
    @isTest
    static void testGetGames() {
        SObjectFactory playerFactory = new test_f_PlayerShortExpFactory();
        Player__c player = (Player__c)playerFactory.buildAndInsertRecord();
        SObjectFactory seasonFactory = new test_f_SeasonFactory();
        Season__c season = (Season__c)seasonFactory.buildAndInsertRecord();
        List<Game__c> games = new List<Game__c>();
        for (Integer i = 0; i < 10; i++) {
            Game__c game = new Game__c(
                Name = 'Game' + i,
            	GameId__c = '123' + i,
            	Player__c = player.Id,
            	Season__c = season.Id);
            games.add(game);
        }
        insert games;
        
        
        Test.startTest();
        List<Game__c> returnedGames = page_DetailCardsController.getGames(player.Id, season.Id);
        Test.stopTest();
        
        System.assertEquals(10, returnedGames.size(), 'a correct number of records should have been returned');
    }
}