temp/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>AST__c</fullName>
        <label>AST</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BLK__c</fullName>
        <label>BLK</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DREB__c</fullName>
        <label>DREB</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FG3A__c</fullName>
        <label>FG3A</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FG3M__c</fullName>
        <label>FG3M</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FG3__c</fullName>
        <label>FG3 %</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FGA__c</fullName>
        <label>FGA</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FGM__c</fullName>
        <label>FGM</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FG__c</fullName>
        <label>FG %</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FTA__c</fullName>
        <label>FTA</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FTM__c</fullName>
        <label>FTM</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FT__c</fullName>
        <label>FT %</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GameId__c</fullName>
        <externalId>true</externalId>
        <label>GameId</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Game_Date__c</fullName>
        <label>Game Date</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MIN__c</fullName>
        <label>MIN</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OREB__c</fullName>
        <label>OREB</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PF__c</fullName>
        <label>PF</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PTS__c</fullName>
        <label>PTS</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plus_minus__c</fullName>
        <label>+/-</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>REB__c</fullName>
        <label>REB</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STL__c</fullName>
        <label>STL</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TOV__c</fullName>
        <label>TOV</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>W_L__c</fullName>
        <label>W/L</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Game</label>
    <nameField>
        <label>Matchup</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>ExternalID</label>
        <length>8</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>First_Name__c  &amp; &quot; &quot; &amp;  Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Potential_Prospect__c.object
<CustomObject>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>ExternalID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>First_Name__c  &amp; &quot; &quot; &amp;  Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Potential Prospect</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Potential Prospects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Season__c.object
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/classes/NewProspectController.cls
public with sharing class NewProspectController {
	@AuraEnabled
    public static String getExternalPlayerID(String fullName, String team) {
        String result;
        List<Potential_Prospect__c> selectedPlayer = [SELECT ExternalID__c FROM Potential_Prospect__c WHERE Full_Name__c =: fullName AND Team__c =: team];
        if (selectedPlayer.size() == 1) {
            result = selectedPlayer[0].ExternalID__c;
        }
        return result;
    }
    @AuraEnabled
    public static PlayerResponse playerCallout(String externalId) {
        try {
			String endpoint = 'https://stats.nba.com/stats/commonplayerinfo/?PlayerId=' + externalId;
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setMethod('GET');
            request.setEndpoint(endpoint);
            HttpResponse response = http.send(request);
            PlayerResponse playerRsp = (PlayerResponse)JSON.deserialize(response.getBody(), PlayerResponse.class);
            return playerRsp;
        } catch (Exception e) {
            String message = 'Error: ' + e.getMessage();
            AuraHandledException auraError = new AuraHandledException(message);
            auraError.setMessage(message);
            throw auraError;
        }
    }
    @AuraEnabled
    public static void deleteProspect(String externalId) {
        List<Potential_Prospect__c> playerToDelete = [SELECT Id FROM Potential_Prospect__c WHERE ExternalID__c =: externalId];
        try {
            delete playerToDelete;
        } catch (DMLException e) {
            String message = 'Error: ' + e.getMessage();
            AuraHandledException auraError = new AuraHandledException(message);
            auraError.setMessage(message);
            throw auraError;
        }
    }
    @AuraEnabled
    public static void gameCallout(String externalId, String seasonExp) {
        try {
            Integer i = 0;
            Integer numberOfSeasons = HttpCalloutHelper.getNumberOfSeasonsToTrack(seasonExp);
            Player__c player = HttpCalloutHelper.getPlayerByExtId(externalId);
            Map<String, Season__c> mapSeasons = HttpCalloutHelper.getSeasonsToTrack(numberOfSeasons);
            List<Game__c> games = new List<Game__c>();
            Set<Id> seasonsIds = new Set<Id>();
            do {
                String currentSeason = HttpCalloutHelper.getSeason(i);
                String endpoint = 'https://stats.nba.com/stats/playergamelog/?PlayerID=' +
                    externalId + '&Season=' + currentSeason + '&SeasonType=Regular%20Season';
                Http http = new Http();
                HttpRequest request = new HttpRequest();
                request.setEndpoint(endpoint);
                request.setMethod('GET');
                HttpResponse response = http.send(request);
                GameResponse gameRsp = (GameResponse)JSON.deserialize(response.getBody(), GameResponse.class);
                if (response.getStatusCode() == 200) {
                    List<List<String>> rows = gameRsp.resultSets[0].rowSet;
                    for (List<String> row : rows) {
                        Game__c newGame = new Game__c(
                            Plus_minus__c = Integer.valueOf(row[25]),
                            AST__c = Integer.valueOf(row[19]),
                            BLK__c = Integer.valueOf(row[21]),
                            DREB__c = Integer.valueOf(row[17]),
                            FG__c = Decimal.valueOf(row[9]),
                            FG3__c = Decimal.valueOf(row[12]),
                            FG3A__c = Integer.valueOf(row[11]),
                            FG3M__c = Integer.valueOf(row[10]),
                            FGA__c = Integer.valueOf(row[8]),
                            FGM__c = Integer.valueOf(row[7]),
                            FT__c = Decimal.valueOf(row[15]),
                            FTA__c = Integer.valueOf(row[14]),
                            FTM__c = Integer.valueOf(row[13]),
                            Game_Date__c = row[3],
                            Name = row[4],
                            GameId__c = row[2]+row[1],
                            MIN__c = Integer.valueOf(row[6]),
                            OREB__c = Integer.valueOf(row[16]),
                            PF__c = Integer.valueOf(row[23]),
                            Player__c = player.Id,
                            PTS__c = Integer.valueOf(row[24]),
                            REB__c = Integer.valueOf(row[18]),
                            Season__c = mapSeasons.get(currentSeason).Id,
                            STL__c = Integer.valueOf(row[20]),
                            TOV__c = Integer.valueOf(row[22]),
                            W_L__c = row[5]
                        );
                        games.add(newGame);
                        seasonsIds.add(mapSeasons.get(currentSeason).Id);
                    }                
                } else {
                    System.debug('something goes wrong');
                }
                i++;
            } while(i <= numberOfSeasons);
            // upsert games based on externalId concatenated with playerId
            database.upsert(games, Game__c.Fields.GameId__c);
            // add season average game records
            List<Game__c> seasonStats = HttpCalloutHelper.getSeasonAverageStats(seasonsIds, player.Id);
            database.upsert(seasonStats, Game__c.Fields.GameId__c);
        } catch (Exception e) {
            String message = 'Error: ' + e.getMessage();
            AuraHandledException auraError = new AuraHandledException(message);
            auraError.setMessage(message);
            throw auraError;
        }
    }
}