temp/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>AST__c</fullName>
        <label>AST</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BLK__c</fullName>
        <label>BLK</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DREB__c</fullName>
        <label>DREB</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FG3A__c</fullName>
        <label>FG3A</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FG3M__c</fullName>
        <label>FG3M</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FG3__c</fullName>
        <label>FG3 %</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FGA__c</fullName>
        <label>FGA</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FGM__c</fullName>
        <label>FGM</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FG__c</fullName>
        <label>FG %</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FTA__c</fullName>
        <label>FTA</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FTM__c</fullName>
        <label>FTM</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FT__c</fullName>
        <label>FT %</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Game_Date__c</fullName>
        <label>Game Date</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MIN__c</fullName>
        <label>MIN</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Games__c</fullName>
        <label>Games</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OREB__c</fullName>
        <label>OREB</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PF__c</fullName>
        <label>PF</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PTS__c</fullName>
        <label>PTS</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plus_minus__c</fullName>
        <label>+/-</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>REB__c</fullName>
        <label>REB</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STL__c</fullName>
        <label>STL</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TOV__c</fullName>
        <label>TOV</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>W_L__c</fullName>
        <label>W/L</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Game</label>
    <nameField>
        <label>Matchup</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Player__c.object
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Season__c.object
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/page_DetailCardsController.cls
public with sharing class page_DetailCardsController {
	@AuraEnabled
    public static Id getCurrentSeasonId() {
        SeasonInfo sInfo = new SeasonInfo(Date.today());
        
        if (Test.isRunningTest()) {
            sInfo = (SeasonInfo)Test.createStub(SeasonInfo.class, new SeasonInfoAugustMock());
        } 
        String currentSeason = sInfo.getCurrentSeasonName();
        Season__c season = [SELECT Id FROM Season__c WHERE Name = :currentSeason LIMIT 1];
        return season.Id;
    }
    
    @AuraEnabled
    public static List<Game__c> getGames(Id playerId, Id seasonId) {
        List<Game__c> games = [SELECT Plus_minus__c, AST__c, BLK__c, DREB__c, FG__c,
                              FG3__c, FG3A__c, FG3M__c, FGA__c, FGM__c, FT__c, FTA__c,
                              FTM__c, Game_Date__c, Name, MIN__c, OREB__c, PF__c,
                              PTS__c, REB__c, STL__c, TOV__c, W_L__c, Number_of_Games__c 
                              FROM Game__c
                              WHERE Player__c = :playerId AND Season__c = :seasonId ORDER BY Game_Date__c DESC];
        return games;
    }
}