temp/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>AST__c</fullName>
        <label>AST</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BLK__c</fullName>
        <label>BLK</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DREB__c</fullName>
        <label>DREB</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FG3A__c</fullName>
        <label>FG3A</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FG3M__c</fullName>
        <label>FG3M</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FG3__c</fullName>
        <label>FG3 %</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FGA__c</fullName>
        <label>FGA</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FGM__c</fullName>
        <label>FGM</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FG__c</fullName>
        <label>FG %</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FTA__c</fullName>
        <label>FTA</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FTM__c</fullName>
        <label>FTM</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FT__c</fullName>
        <label>FT %</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GameId__c</fullName>
        <externalId>true</externalId>
        <label>GameId</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Game_Date__c</fullName>
        <label>Game Date</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MIN__c</fullName>
        <label>MIN</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OREB__c</fullName>
        <label>OREB</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PF__c</fullName>
        <label>PF</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PTS__c</fullName>
        <label>PTS</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plus_minus__c</fullName>
        <label>+/-</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>REB__c</fullName>
        <label>REB</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STL__c</fullName>
        <label>STL</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TOV__c</fullName>
        <label>TOV</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>W_L__c</fullName>
        <label>W/L</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Game</label>
    <nameField>
        <label>Matchup</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Player__c.object
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Season__c.object
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/classes/test_ReturnedGames.cls
@isTest
private class test_ReturnedGames {
    @isTest
    static void testManageReturnedRecords() {
        SObjectFactory playerFactory = new test_f_PlayerFactory();
        Player__c player = (Player__c)playerFactory.buildAndInsertRecord();
        SobjectFactory seasonFactory = new test_f_SeasonFactory();
        Season__c season = (Season__c)seasonFactory.buildAndInsertRecord();
        HttpResponse response = test_f_HttpResponseFactory.getGames();
        ReturnedGames retGames = new ReturnedGames(player.Id, season.Id);
        
        Test.startTest();
        List<Game__c> games = retGames.manageReturnedRecords(response);
        Test.stopTest();
        system.debug(String.valueOf(games[0]));
        Integer numbOfGames = 3;
        String gameToString = 'Game__c:{Plus_minus__c=-4, AST__c=1, BLK__c=1, DREB__c=4, FG__c=0.500, FG3__c=0.400, ' +
            				'FG3A__c=5, FG3M__c=2, FGA__c=6, FGM__c=3, FT__c=0.000, FTA__c=0, FTM__c=0, Game_Date__c=APR 11, 2018, Name=BKN @ BOS, ' +
            				'GameId__c=0021701219203112, MIN__c=24, OREB__c=1, PF__c=2, Player__c=' + player.Id + ', ' +
            				'PTS__c=8, REB__c=5, Season__c=' + season.Id + ', STL__c=1, TOV__c=1, W_L__c=L}';
        
        System.assertEquals(numbOfGames, games.size(), 'there should have been 3 games records');
        System.assertEquals(gameToString, String.valueOf(games[0]), 'a response should have been correctly deserialized');
    }
}