temp/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>ExternalID</label>
        <length>8</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Season_Experience__c</fullName>
        <label>Season experience</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team_Abbreviation__c</fullName>
        <label>Team Abbreviation</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Name__c</fullName>
        <label>Team Name</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/test_f_PlayerFactory.cls
@isTest
public class test_f_PlayerFactory extends SObjectFactory {
	public SObject buildRecordWithData() {
        Integer tempCounter = counter;
        return new Player__c(
        	First_Name__c = 'Test',
        	Name = 'Player' + tempCounter,
        	Team_Abbreviation__c = 'TST',
        	Team_Name__c = 'Test Team',
        	ExternalID__c = '12345' + tempCounter,
        	Birthdate__c = Date.newInstance(1995, 1, 1),
        	Country__c = 'USA',
        	Height__c = '6ft 6in',
        	Position__c = 'SF',
        	School__c = 'Duke',
        	Season_Experience__c = 4,
        	Weight__c = '210lbs');
    }
}