temp/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>ExternalID</label>
        <length>8</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/test_EndpointFactory.cls
@isTest
private class test_EndpointFactory {
    @isTest
    static void testGetInstance() {
        SObjectFactory playerFactory = new test_f_PlayerFactory();
       	Player__c player = (Player__c)playerFactory.buildAndInsertRecord();
        
        Test.startTest();
        INbaEndpoint prospectsInstance = EndpointFactory.getInstance('Prospects');
        INbaEndpoint playerInstance = EndpointFactory.getInstance('Player', player.ExternalId__c);
        INbaEndpoint gamesInstance = EndpointFactory.getInstance('Games', player.ExternalId__c, 0);
        INbaEndpoint nullInstance = EndpointFactory.getInstance('test');
        Test.stopTest();
        
        System.assertEquals(true, prospectsInstance instanceOf ProspectsEndpoint, 'correct type of instance should have been returned');
        System.assertEquals(true, playerInstance instanceOf PlayerEndpoint, 'correct type of instance should have been returned');
        System.assertEquals(true, gamesInstance instanceOf GamesEndpoint, 'correct type of instance should have been returned');
        System.assertEquals(null, nullInstance, 'null value should have been returned');
    }
}