temp/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>ExternalID</label>
        <length>8</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Season_Experience__c</fullName>
        <label>Season experience</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Season__c.object
<CustomObject>
    <fields>
        <fullName>Number__c</fullName>
        <label>Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PlayerExperienceInfo.cls
public class PlayerExperienceInfo {
	private static PlayerExperienceInfo instance = null;
    public List<Season__c> seasons {get; private set;}
    
    private PlayerExperienceInfo(String externalId, SeasonInfo sInfo) {
        seasons = new List<Season__c>();
        getListOfSeasonsToTrack(externalId, sInfo);
    }
    
    private void getListOfSeasonsToTrack(String externalId, SeasonInfo sInfo) {
        // get the starting year of the player's first season
        Player__c player = [SELECT Season_Experience__c FROM Player__c WHERE ExternalID__c = :externalId LIMIT 1];
        // get a number of seasons to track based on player's experiance
        Integer numberOfFullSeasons = Integer.valueOf(player.Season_Experience__c);
        List<String> seasonsNames = new List<String>();
        
        for (Integer i = 0; i < numberOfFullSeasons; i++) {
            seasonsNames.add(sInfo.getSeasonName(i));
        }
        // include one more season if current one is still going
        if (!sInfo.isSeasonEnded()) {
            seasonsNames.add(sInfo.getSeasonName(numberOfFullSeasons));
        }
        // create list of all seasons to track  
        seasons = [SELECT Id, Name, Number__c FROM Season__c WHERE Name IN :seasonsNames];
    }
    
    // lazy load of PlayerExperienceInfo instance
    public static PlayerExperienceInfo getInstance(String externalId, SeasonInfo sInfo) {
        if (instance == null) instance = new PlayerExperienceInfo(externalId, sInfo);
        return instance;
    }
}