temp/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Season_Experience__c</fullName>
        <label>Season experience</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Season__c.object
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/test_SelectSeasonController.cls
@isTest
private class test_SelectSeasonController {
	@isTest
    static void testGetSeasons() {
        SObjectFactory playerFactory = new test_f_PlayerFactory();
        Player__c player = (Player__c)playerFactory.buildAndInsertRecord();
        SObjectFactory seasonFactory = new test_f_SeasonFactory();
        seasonFactory.buildAndInsertRecords(Integer.valueOf(player.Season_Experience__c) + 1);
        
        Test.startTest();
        List<Season__c> seasons = page_SelectSeasonController.getSeasons(player.Id);
        Test.stopTest();
        
        System.assertEquals(player.Season_Experience__c, seasons.size(), 'a correct number of the seasons should have been returned');
    }
}