temp/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>ExternalID</label>
        <length>8</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Season_Experience__c</fullName>
        <label>Season experience</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team_Abbreviation__c</fullName>
        <label>Team Abbreviation</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Name__c</fullName>
        <label>Team Name</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ReturnedPlayer.cls
public class ReturnedPlayer implements IReturnedRecords {
	public List<Player__c> manageReturnedRecords(HttpResponse response) {
        List<String> profile = deserializeRespone(response);
        List<Player__c> players = new List<Player__c>();
        Player__c player = new Player__c(
        	First_Name__c = profile[1],
        	Name = profile[2],
        	Team_Abbreviation__c = profile[18],
        	Team_Name__c = profile[20] + ' ' + profile[17],
        	ExternalID__c = profile[0],
        	Birthdate__c = Date.valueOf(profile[6]),
        	Country__c = profile[8],
        	Height__c = profile[10].split('-')[0] + 'ft ' + profile[10].split('-')[1] + 'in',
        	Position__c = profile[14],
        	School__c = profile[7],
        	Season_Experience__c = Integer.valueOf(profile[12]),
        	Weight__c = profile[11] + 'lbs');
        players.add(player);
        return players;
    }
    
    // Deserialize the response into a list of records 
    private List<String> deserializeRespone(HttpResponse response) {
        PlayerResponse playerRsp = (PlayerResponse)JSON.deserialize(response.getBody(), PlayerResponse.class);
        return playerRsp.resultSets[0].rowSet[0];
    }
}