temp/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>ExternalID</label>
        <length>8</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Season_Experience__c</fullName>
        <label>Season experience</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team_Abbreviation__c</fullName>
        <label>Team Abbreviation</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Name__c</fullName>
        <label>Team Name</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/test_ReturnedPlayer.cls
@isTest
public class test_ReturnedPlayer {
	@isTest
    static void testManageReturnedRecords() {
        HttpResponse response = test_f_HttpResponseFactory.getPlayer();
        ReturnedPlayer retPlayer = new ReturnedPlayer();
        
        Test.startTest();
        List<Player__c> player = retPlayer.manageReturnedRecords(response);
        Test.stopTest();
        
        Integer numbOfPlayers = 1;
        String playerToString = 'Player__c:{First_Name__c=Quincy, Name=Acy, Team_Abbreviation__c=BKN, Team_Name__c=Brooklyn Nets, ' +
            					'ExternalID__c=203112, Birthdate__c=1990-10-06 00:00:00, Country__c=USA, Height__c=6ft 7in, ' +
                				'Position__c=Forward, School__c=Baylor, Season_Experience__c=6, Weight__c=240lbs}';
        
        System.assertEquals(numbOfPlayers, player.size(), 'there should have been only player record');
        System.assertEquals(playerToString, String.valueOf(player[0]), 'a response should have been correctly deserialized');
    }
}