temp/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>ExternalID</label>
        <length>8</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Season__c.object
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/classes/page_SelectSeasonController.cls
public with sharing class page_SelectSeasonController {
	@AuraEnabled
    // Get a list of all seasons by given player
    public static List<Season__c> getSeasons(Id playerId) {
        SeasonInfo sInfo = new SeasonInfo(Date.today());
        if (Test.isRunningTest()) {
            sInfo = (SeasonInfo)Test.createStub(SeasonInfo.class, new SeasonInfoAugustMock());
        } 
        // Get player's external Id
        Player__c player = [SELECT ExternalId__c FROM Player__c WHERE Id =: playerId LIMIT 1];
        // Get a list of player's seasons
        List<Season__c> seasonsList = PlayerExperienceInfo.getInstance(player.ExternalID__c, sInfo).seasons;
        return seasonsList;
    }
}