temp/objects/Potential_Prospect__c.object
<CustomObject>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>ExternalID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>First_Name__c  &amp; &quot; &quot; &amp;  Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Potential Prospect</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Potential Prospects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProspectInfo.cls
public class ProspectInfo {
	private static ProspectInfo instance = null;
    public Potential_Prospect__c prospect {get; private set;}
    
    private ProspectInfo(String fullName, String team) {
        prospect = [SELECT ExternalID__c FROM Potential_Prospect__c WHERE Full_Name__c =: fullName AND Team__c =: team LIMIT 1];
    }
    
    // lazy load of ProspectInfo instance
    public static ProspectInfo getInstance(String fullName, String team) {
        if (instance == null) instance = new ProspectInfo(fullName, team);
        return instance;
    }
}