temp/objects/Potential_Prospect__c.object
<CustomObject>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>First_Name__c  &amp; &quot; &quot; &amp;  Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Potential Prospect</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Potential Prospects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/classes/page_PlayerPicklistController.cls
public with sharing class page_PlayerPicklistController {
	@AuraEnabled
    // Get all players names by team
    public static List<String> getPicklistValues(String team) {
        List<String> players = new List<String>();
        for (Potential_Prospect__c prospect : [SELECT Full_Name__c FROM Potential_Prospect__c WHERE Team__c = :team]) {
            players.add(prospect.Full_Name__c);
        }
        players.sort();
        
        return players;
    } 
}