temp/objects/Potential_Prospect__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Potential Prospect</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Potential Prospects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/classes/test_TeamPicklistController.cls
@isTest
private class test_TeamPicklistController {
	@isTest
    static void testGetPicklistValues() {
        SObjectFactory prospectFactory = new test_f_PotentialProspectFactory();
        List<Potential_Prospect__c> prospects = (List<Potential_Prospect__c>)prospectFactory.buildAndInsertRecords(10);
        String team = prospects[0].Team__c;
        
        Test.startTest();
        List<String> teams = page_TeamPicklistController.getPicklistValues();
        Test.stopTest();
        
        System.assertEquals(team, teams[0], 'a correct team name should have been returned');
        System.assertEquals(1, teams.size(), 'a correcut number of strings should have been returned');
    }
}