temp/objects/Potential_Prospect__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Potential Prospect</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Potential Prospects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/classes/test_PlayerPicklistController.cls
@isTest
private class test_PlayerPicklistController {
	@isTest
    static void testGetPicklistValues() {
        SObjectFactory prospectFactory = new test_f_PotentialProspectFactory();
        List<Potential_Prospect__c> prospects = (List<Potential_Prospect__c>)prospectFactory.buildAndInsertRecords(10);
        String team = prospects[0].Team__c;
        
        Test.startTest();
        List<String> retrievedProspects = page_PlayerPicklistController.getPicklistValues(team);
        Test.stopTest();
        
        System.assertEquals(prospects.size(), retrievedProspects.size(), 'a correct number of records names should have been returned');
    }
}