temp/objects/Potential_Prospect__c.object
<CustomObject>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>ExternalID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Potential Prospect</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Potential Prospects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/page_RefreshProspectsController.cls
public with sharing class page_RefreshProspectsController {
	@AuraEnabled
    // Make a callout to retrieve list of potential prospects
    public static void prospectsCallout() {
        IWebServiceFactory prospectsCallout = new ProspectsCallout();
        AssembleCallout callout = new AssembleCallout(prospectsCallout);
        List<sObject> objects = callout.makeCallout();
        // Save records to the database
        try {
            database.upsert((List<Potential_Prospect__c>)objects, Potential_Prospect__c.Fields.ExternalID__c); 
            system.debug('success');              
        } catch(DMLException e) {
        	system.debug(e.getMessage());
        }
    }
}